// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnvIM-uWIbZ9vmbKQpjIU9raEko4VjdBg',
    appId: '1:527669672147:web:406e3ded558c769b3efc26',
    messagingSenderId: '527669672147',
    projectId: 'beaming-glyph-471220-j6',
    authDomain: 'beaming-glyph-471220-j6.firebaseapp.com',
    storageBucket: 'beaming-glyph-471220-j6.firebasestorage.app',
    measurementId: 'G-0QL6EXNZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAS6UjRZ9uApgHv1gn3AhWiHmQeCJr_8',
    appId: '1:527669672147:android:e84ec0fb9f667ead3efc26',
    messagingSenderId: '527669672147',
    projectId: 'beaming-glyph-471220-j6',
    storageBucket: 'beaming-glyph-471220-j6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2pN5DZzPGR3fqseuHi0KXxE-dxgC2LXU',
    appId: '1:527669672147:ios:3bcb103949513cf43efc26',
    messagingSenderId: '527669672147',
    projectId: 'beaming-glyph-471220-j6',
    storageBucket: 'beaming-glyph-471220-j6.firebasestorage.app',
    iosBundleId: 'com.example.aiModels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2pN5DZzPGR3fqseuHi0KXxE-dxgC2LXU',
    appId: '1:527669672147:ios:3bcb103949513cf43efc26',
    messagingSenderId: '527669672147',
    projectId: 'beaming-glyph-471220-j6',
    storageBucket: 'beaming-glyph-471220-j6.firebasestorage.app',
    iosBundleId: 'com.example.aiModels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnvIM-uWIbZ9vmbKQpjIU9raEko4VjdBg',
    appId: '1:527669672147:web:6be1e0ff558ed5823efc26',
    messagingSenderId: '527669672147',
    projectId: 'beaming-glyph-471220-j6',
    authDomain: 'beaming-glyph-471220-j6.firebaseapp.com',
    storageBucket: 'beaming-glyph-471220-j6.firebasestorage.app',
    measurementId: 'G-3TBJJHX7KX',
  );
}
